image: Visual Studio 2019 Preview
  
before_build:
  - git clone https://github.com/rgalarcia/Idefix.git
  - cmd: cd Idefix  
  - cmd: nuget restore

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

build:
  project:  C:\projects\idefix-release\Idefix\Idefix.sln    # path to Visual Studio solution or project
  parallel: false                                       # enable MSBuild parallel builds
  verbosity: normal                                     # MSBuild verbosity level (quiet|minimal|normal|detailed)

after_build:
  - 7z a Idefix.7z "%APPVEYOR_BUILD_FOLDER%\Idefix\Idefix\bin\Debug"

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Debug\*
  - path: Idefix\Idefix.zip
    name: artifacts-all
    
deploy:
  release: v$(appveyor_build_version)
  description: idefix_release
  tag: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
     secure: yrM69KAMKsN0o1btzkUu5VaJuPoP5UeLEjXAL5Mk1/30WiPKeryMi0GE/PcIy6DO
  artifact: 'Idefix\Idefix.7z'    
    
